-- MySQL Script generated by MySQL Workbench
-- Fri 08 Mar 2019 05:41:05 PM MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema olympics_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olympics_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olympics_data` DEFAULT CHARACTER SET utf8mb4 ;
USE `olympics_data` ;

-- -----------------------------------------------------
-- Table `olympics_data`.`dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olympics_data`.`dictionary` ;

CREATE TABLE IF NOT EXISTS `olympics_data`.`dictionary` (
  `Country` TEXT NULL DEFAULT NULL,
  `Code` TEXT NULL DEFAULT NULL,
  `Population` INT(11) NULL DEFAULT NULL,
  `GDP per Capita` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olympics_data`.`summer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olympics_data`.`summer` ;

CREATE TABLE IF NOT EXISTS `olympics_data`.`summer` (
  `Year` INT(11) NULL DEFAULT NULL,
  `City` TEXT NULL DEFAULT NULL,
  `Sport` TEXT NULL DEFAULT NULL,
  `Discipline` TEXT NULL DEFAULT NULL,
  `Athlete` TEXT NULL DEFAULT NULL,
  `Country` TEXT NULL DEFAULT NULL,
  `Gender` TEXT NULL DEFAULT NULL,
  `Event` TEXT NULL DEFAULT NULL,
  `Medal` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olympics_data`.`winter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olympics_data`.`winter` ;

CREATE TABLE IF NOT EXISTS `olympics_data`.`winter` (
  `Year` INT(11) NULL DEFAULT NULL,
  `City` TEXT NULL DEFAULT NULL,
  `Sport` TEXT NULL DEFAULT NULL,
  `Discipline` TEXT NULL DEFAULT NULL,
  `Athlete` TEXT NULL DEFAULT NULL,
  `Country` TEXT NULL DEFAULT NULL,
  `Gender` TEXT NULL DEFAULT NULL,
  `Event` TEXT NULL DEFAULT NULL,
  `Medal` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
